if(NOT DEFINED STAGE_DIR OR NOT DEFINED SLUG)
    message(FATAL_ERROR "STAGE_DIR and SLUG are required")
endif()

if(APPLE)
    set(standalone "${STAGE_DIR}/standalone/${SLUG}_standalone_plugin.app")
elseif(WIN32)
    set(standalone "${STAGE_DIR}/standalone/${SLUG}_standalone_plugin.exe")
else()
    set(standalone "${STAGE_DIR}/standalone/${SLUG}_standalone_plugin")
endif()
set(vst3 "${STAGE_DIR}/vst3/${SLUG}_vst3_plugin.vst3")
set(manifest "${STAGE_DIR}/ARTIFACTS.txt")

foreach(path IN ITEMS "${standalone}" "${vst3}" "${manifest}")
    if(NOT EXISTS "${path}")
        message(FATAL_ERROR "Missing staged artifact: ${path}")
    endif()
endforeach()

if(WIN32 AND NOT IS_DIRECTORY "${vst3}")
    message(FATAL_ERROR "Windows VST3 must be staged as a directory bundle: ${vst3}")
endif()

if(EXPECT_AU)
    set(au "${STAGE_DIR}/au/${SLUG}_au_plugin.component")
    if(NOT EXISTS "${au}")
        message(FATAL_ERROR "Missing staged AU: ${au}")
    endif()
    foreach(bundle IN ITEMS "${standalone}" "${vst3}" "${au}")
        execute_process(COMMAND codesign --verify --deep --strict "${bundle}" RESULT_VARIABLE result ERROR_VARIABLE error)
        if(NOT result EQUAL 0)
            message(FATAL_ERROR "Invalid ad-hoc signature for ${bundle}: ${error}")
        endif()
    endforeach()
endif()
