name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: EsionHsrahLatigid/juce-ci/.github/workflows/plugin-release.yml@926c5bb10335c29503f92869169759ec18d71449
    permissions:
      actions: read
      contents: write
    with:
      product_name: StaticCathedral
