name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: EsionHsrahLatigid/juce-ci/.github/workflows/plugin-release.yml@6182ac7554be6df6dee46d1e75eb097fde97abaf
    permissions:
      actions: read
      contents: write
    with:
      product_name: StaticCathedral
